from pydantic import BaseModel
from enum import Enum

class ApplicationBase(BaseModel):
    job_id: int
    
class ApplicationOut(BaseModel):
    # The unique ID of the application, generated by the database.
    id: int
    # The ID of the job the user applied for.
    job_id: int
    # The ID of the user (job seeker) who submitted the application.
    user_id: int
    # The status of the application (e.g., "pending," "accepted").
    # It's a string, matching the database representation
    status: str

    class Config:
        orm_mode = True